### PR TITLE
dockerizing the cli

### PR DESCRIPTION
**Pull request by leopoldodonnell**
Currently the structurizr cli requires users to have java correctly installed. While most people have docker nowadays, many do not have a working java environment on their workstations. This PR provides a path for those developers.

### CODE REVIEW

**Comment by leopoldodonnell** [comment]
Please consider this PR, I think it would be useful. I have not added a windows based script as I do not have a windows based workstation to test on.

Happy to do a little more work if more documentation is needed. 

Note: I'm using my personal dockerhub account ATM, but would update the code to point to structurizr before merging.
Code changes would be needed in `docker.yml` and in `docker/structurizr`

**Comment by simonbrowndotje** [comment]
Thanks for this. I'd rather not have anything deployment related (e.g. Homebrew, Docker, etc) in this repo, so if you the host the Dockerfile and instructions in your own repo, I'll add a link so that others can find it.

**Comment by leopoldodonnell** [comment]
No problem at all. I’ve just got to think it through so it can live
separately from the code.

**Comment by leopoldodonnell** [comment]
I have modified and moved this feature to the repo: http://github.com/leopoldodonnell/structurizr-cli-docker which will build a docker container on dockerhub for the repo: `leopoldodonnell/structurizr-cli`

**Comment by simonbrowndotje** [comment]
Thanks, I've added a link from the [getting started page](https://github.com/structurizr/cli/blob/master/docs/getting-started.md#docker).

**Comment by aidmax** [comment]
Thanks @simonbrowndotje  for pointing to my repo as well 👍

**Pull request closed without merging**
